object Form1: TForm1
  Left = 0
  Top = 0
  Caption = 'Form1'
  ClientHeight = 556
  ClientWidth = 673
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Memo1: TMemo
    Left = 0
    Top = 0
    Width = 185
    Height = 525
    Align = alLeft
    Lines.Strings = (
      '{'
      '  "data": {'
      '    "participante": ['
      '      {'
      '        "id_participante": 1,'
      '        "id_empresa": 1,'
      '        "nome": "Daiane",'
      '        "dt_nasc_criacao": null,'
      '        "ddd1": null,'
      '        "telefone1": null,'
      '        "ddd2": null,'
      '        "telefone2": null,'
      '        "email": null,'
      '        "rg": null,'
      '        "apelido": null,'
      '        "cpf_cnpj": null,'
      '        "isuf": null,'
      '        "id_crt": 0,'
      '        "id_porte_empresa": 0,'
      '        "id_tipo_atividade": 0,'
      '        "suframa": null,'
      '        "id_contribuinte": 0,'
      '        "id_classe": 0,'
      '        "numero_original": 0,'
      '        "fabricante": true,'
      '        "tipo_participante": 0,'
      '        "participante_ref": 0,'
      '        "cod_ref": -1,'
      '        "consumidor_final": false,'
      '        "part_enderecos": [],'
      '        "part_administradora": {},'
      '        "part_cliente": {},'
      '        "part_contador": {},'
      '        "part_fornecedor": {'
      '          "id_fornecedor": 1,'
      '          "id_participante": 1,'
      '          "id_empresa": 1,'
      '          "contato": null,'
      '          "contato_tel": null,'
      '          "status": 0,'
      '          "cod_ref_fornecedor": 0,'
      '          "cod_ref": 0'
      '        },'
      '        "part_funcionario": {'
      '          "id_participante": 1,'
      '          "id_empresa": 1,'
      '          "status": 1,'
      '          "entrada_servico": null,'
      '          "saida_servico": null,'
      '          "cod_ref": 0,'
      '          "id_funcionario": 2'
      '        },'
      '        "part_motorista": {'
      '          "id_motorista": 4,'
      '          "id_participante": 1,'
      '          "id_empresa": 1,'
      '          "status": false,'
      '          "numero_cnh": "45775656",'
      '          "cnh_data_emissao": "2022-'
      '01-28",'
      '          "cnh_data_validade": "2032'
      '-01-28",'
      '          "cnh_data_primeira": null,'
      '          "cnh_categoria": null,'
      '          "part_motorista_ref": 1,'
      '          "cod_ref": 0'
      '        },'
      '        "part_socios": {'
      '          "id_socio": 1,'
      '          "id_participante": 1,'
      '          "id_empresa": 1,'
      '          "status": 1,'
      '          "dt_admissao": null,'
      '          "dt_demissao": null,'
      '          "perc_particiapacao": 1,'
      '          "part_socios_ref": 1,'
      '          "cod_ref": 1'
      '        },'
      '        "part_transportador": {'
      '          "id_transportador": 1,'
      '          "id_participante": 1,'
      '          "id_empresa": 1,'
      '          "placa_veiculo": "15484",'
      '          "uf_veiculo": "BA",'
      '          "cifob": 0,'
      '          "rntc": null,'
      '          "mod_frete": 0,'
      '          "status": 0,'
      '          "id_tipo_proprietario": 1,'
      '          "rntrc": "1332",'
      '          "cod_ref_transportadora": 1,'
      '          "cod_ref": 1'
      '        },'
      '        "part_vendedor": {}'
      '      },'
      #9'  {'
      '        "id_participante": 2,'
      '        "id_empresa": 1,'
      '        "nome": "Daiane",'
      '        "dt_nasc_criacao": null,'
      '        "ddd1": null,'
      '        "telefone1": null,'
      '        "ddd2": null,'
      '        "telefone2": null,'
      '        "email": null,'
      '        "rg": null,'
      '        "apelido": null,'
      '        "cpf_cnpj": null,'
      '        "isuf": null,'
      '        "id_crt": 0,'
      '        "id_porte_empresa": 0,'
      '        "id_tipo_atividade": 0,'
      '        "suframa": null,'
      '        "id_contribuinte": 0,'
      '        "id_classe": 0,'
      '        "numero_original": 0,'
      '        "fabricante": true,'
      '        "tipo_participante": 0,'
      '        "participante_ref": 0,'
      '        "cod_ref": -1,'
      '        "consumidor_final": false,'
      '        "part_enderecos": [],'
      '        "part_administradora": {},'
      '        "part_cliente": {},'
      '        "part_contador": {},'
      '        "part_fornecedor": {'
      '          "id_fornecedor": 1,'
      '          "id_participante": 1,'
      '          "id_empresa": 1,'
      '          "contato": null,'
      '          "contato_tel": null,'
      '          "status": 0,'
      '          "cod_ref_fornecedor": 0,'
      '          "cod_ref": 0'
      '        },'
      '        "part_funcionario": {'
      '          "id_participante": 2,'
      '          "id_empresa": 1,'
      '          "status": 1,'
      '          "entrada_servico": null,'
      '          "saida_servico": null,'
      '          "cod_ref": 0,'
      '          "id_funcionario": 2'
      '        },'
      '        "part_motorista": {'
      '          "id_motorista": 4,'
      '          "id_participante": 2,'
      '          "id_empresa": 1,'
      '          "status": false,'
      '          "numero_cnh": "45775656",'
      '          "cnh_data_emissao": "2022-'
      '01-28",'
      '          "cnh_data_validade": "2032'
      '-01-28",'
      '          "cnh_data_primeira": null,'
      '          "cnh_categoria": null,'
      '          "part_motorista_ref": 1,'
      '          "cod_ref": 0'
      '        },'
      '        "part_socios": {'
      '          "id_socio": 1,'
      '          "id_participante": 2,'
      '          "id_empresa": 1,'
      '          "status": 1,'
      '          "dt_admissao": null,'
      '          "dt_demissao": null,'
      '          "perc_particiapacao": 1,'
      '          "part_socios_ref": 1,'
      '          "cod_ref": 1'
      '        },'
      '        "part_transportador": {'
      '          "id_transportador": 1,'
      '          "id_participante": 2,'
      '          "id_empresa": 1,'
      '          "placa_veiculo": "15484",'
      '          "uf_veiculo": "BA",'
      '          "cifob": 0,'
      '          "rntc": null,'
      '          "mod_frete": 0,'
      '          "status": 0,'
      '          "id_tipo_proprietario": 1,'
      '          "rntrc": "1332",'
      '          "cod_ref_transportadora": 1,'
      '          "cod_ref": 1'
      '        },'
      '        "part_vendedor": {}'
      '      }'
      '    ]'
      '  },'
      '  "structure": {'
      '    "participante": ['
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "nome",'
      '        "dataType": "ftString",'
      '        "size": 100'
      '      },'
      '      {'
      '        "fieldName": '
      '"dt_nasc_criacao",'
      '        "dataType": "ftDate",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "ddd1",'
      '        "dataType": "ftString",'
      '        "size": 2'
      '      },'
      '      {'
      '        "fieldName": "telefone1",'
      '        "dataType": "ftString",'
      '        "size": 9'
      '      },'
      '      {'
      '        "fieldName": "ddd2",'
      '        "dataType": "ftString",'
      '        "size": 2'
      '      },'
      '      {'
      '        "fieldName": "telefone2",'
      '        "dataType": "ftString",'
      '        "size": 9'
      '      },'
      '      {'
      '        "fieldName": "email",'
      '        "dataType": "ftString",'
      '        "size": 60'
      '      },'
      '      {'
      '        "fieldName": "rg",'
      '        "dataType": "ftString",'
      '        "size": 20'
      '      },'
      '      {'
      '        "fieldName": "apelido",'
      '        "dataType": "ftString",'
      '        "size": 100'
      '      },'
      '      {'
      '        "fieldName": "cpf_cnpj",'
      '        "dataType": "ftString",'
      '        "size": 14'
      '      },'
      '      {'
      '        "fieldName": "isuf",'
      '        "dataType": "ftString",'
      '        "size": 10'
      '      },'
      '      {'
      '        "fieldName": "id_crt",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"id_porte_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"id_tipo_atividade",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "suframa",'
      '        "dataType": "ftString",'
      '        "size": 9'
      '      },'
      '      {'
      '        "fieldName": "id_contribuinte",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_classe",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"numero_original",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "fabricante",'
      '        "dataType": "ftBoolean",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"tipo_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"participante_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"consumidor_final",'
      '        "dataType": "ftBoolean",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_enderecos": ['
      '      {'
      '        "fieldName": '
      '"id_part_enderecos",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"id_tipo_endereco",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_uf",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_municipio",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_pais",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cep",'
      '        "dataType": "ftString",'
      '        "size": 15'
      '      },'
      '      {'
      '        "fieldName": '
      '"tipo_logradouro",'
      '        "dataType": "ftString",'
      '        "size": 60'
      '      },'
      '      {'
      '        "fieldName": "logradouro",'
      '        "dataType": "ftString",'
      '        "size": 60'
      '      },'
      '      {'
      '        "fieldName": "numero",'
      '        "dataType": "ftString",'
      '        "size": 10'
      '      },'
      '      {'
      '        "fieldName": "bairro",'
      '        "dataType": "ftString",'
      '        "size": 60'
      '      },'
      '      {'
      '        "fieldName": "complemento",'
      '        "dataType": "ftString",'
      '        "size": 100'
      '      },'
      '      {'
      '        "fieldName": '
      '"cidade_estrangeiro",'
      '        "dataType": "ftString",'
      '        "size": 40'
      '      },'
      '      {'
      '        "fieldName": '
      '"part_enderecos_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_administradora": ['
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"id_administradora",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "status",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "taxa_juros",'
      '        "dataType": "ftFloat",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_conta",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_historico",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_tipo_ajuste",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"cod_ref_administradora",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_cliente": ['
      '      {'
      '        "fieldName": "id_cliente",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"id_cliente_preco",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_cond_pag",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_regiao",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "limite_credito",'
      '        "dataType": "ftFloat",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "conta_credito",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "conta_debito",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_vendedor",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"desconto_maximo",'
      '        "dataType": "ftFloat",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "status",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "dh_insercao",'
      '        "dataType": "ftDateTime",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "dh_alteracao",'
      '        "dataType": "ftDateTime",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref_cliente",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_contador": ['
      '      {'
      '        "fieldName": "id_contador",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"cod_ref_contador",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "crc",'
      '        "dataType": "ftString",'
      '        "size": 15'
      '      },'
      '      {'
      '        "fieldName": '
      '"cnpj_contabilidade",'
      '        "dataType": "ftString",'
      '        "size": 14'
      '      },'
      '      {'
      '        "fieldName": "status",'
      '        "dataType": "ftBoolean",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"part_contador_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_fornecedor": ['
      '      {'
      '        "fieldName": "id_fornecedor",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "contato",'
      '        "dataType": "ftString",'
      '        "size": 60'
      '      },'
      '      {'
      '        "fieldName": "contato_tel",'
      '        "dataType": "ftString",'
      '        "size": 14'
      '      },'
      '      {'
      '        "fieldName": "status",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"cod_ref_fornecedor",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_funcionario": ['
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "status",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"entrada_servico",'
      '        "dataType": "ftDateTime",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "saida_servico",'
      '        "dataType": "ftDateTime",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_funcionario",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_motorista": ['
      '      {'
      '        "fieldName": "id_motorista",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "status",'
      '        "dataType": "ftBoolean",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "numero_cnh",'
      '        "dataType": "ftString",'
      '        "size": 11'
      '      },'
      '      {'
      '        "fieldName": '
      '"cnh_data_emissao",'
      '        "dataType": "ftDate",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"cnh_data_validade",'
      '        "dataType": "ftDate",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"cnh_data_primeira",'
      '        "dataType": "ftDate",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cnh_categoria",'
      '        "dataType": "ftMemo",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"part_motorista_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_socios": ['
      '      {'
      '        "fieldName": "id_socio",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "status",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "dt_admissao",'
      '        "dataType": "ftDate",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "dt_demissao",'
      '        "dataType": "ftDate",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"perc_particiapacao",'
      '        "dataType": "ftFloat",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "part_socios_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_transportador": ['
      '      {'
      '        "fieldName": '
      '"id_transportador",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "placa_veiculo",'
      '        "dataType": "ftString",'
      '        "size": 8'
      '      },'
      '      {'
      '        "fieldName": "uf_veiculo",'
      '        "dataType": "ftString",'
      '        "size": 2'
      '      },'
      '      {'
      '        "fieldName": "cifob",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "rntc",'
      '        "dataType": "ftString",'
      '        "size": 20'
      '      },'
      '      {'
      '        "fieldName": "mod_frete",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "status",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"id_tipo_proprietario",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "rntrc",'
      '        "dataType": "ftString",'
      '        "size": 8'
      '      },'
      '      {'
      '        "fieldName": '
      '"cod_ref_transportadora",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ],'
      '    "part_vendedor": ['
      '      {'
      '        "fieldName": "id_vendedor",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_participante",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "id_empresa",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "comissao",'
      '        "dataType": "ftFloat",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"desconto_maximo",'
      '        "dataType": "ftFloat",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "app_bloq",'
      '        "dataType": "ftString",'
      '        "size": 1'
      '      },'
      '      {'
      '        "fieldName": "app_token",'
      '        "dataType": "ftString",'
      '        "size": 300'
      '      },'
      '      {'
      '        "fieldName": "status",'
      '        "dataType": "ftBoolean",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": '
      '"cod_ref_vendedor",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      },'
      '      {'
      '        "fieldName": "cod_ref",'
      '        "dataType": "ftInteger",'
      '        "size": 0'
      '      }'
      '    ]'
      '  }'
      '}  ')
    TabOrder = 0
  end
  object Memo2: TMemo
    Left = 488
    Top = 0
    Width = 185
    Height = 525
    Align = alRight
    TabOrder = 1
  end
  object DBGrid1: TDBGrid
    Left = 183
    Top = 0
    Width = 306
    Height = 265
    DataSource = dtsPai
    TabOrder = 2
    TitleFont.Charset = DEFAULT_CHARSET
    TitleFont.Color = clWindowText
    TitleFont.Height = -11
    TitleFont.Name = 'Tahoma'
    TitleFont.Style = []
  end
  object DBGrid2: TDBGrid
    Left = 183
    Top = 262
    Width = 306
    Height = 266
    DataSource = dtsFilho
    TabOrder = 3
    TitleFont.Charset = DEFAULT_CHARSET
    TitleFont.Color = clWindowText
    TitleFont.Height = -11
    TitleFont.Name = 'Tahoma'
    TitleFont.Style = []
  end
  object Button1: TButton
    Left = 0
    Top = 525
    Width = 673
    Height = 31
    Align = alBottom
    Caption = 'Button1'
    TabOrder = 4
    OnClick = Button1Click
  end
  object dtsPai: TDataSource
    Left = 450
    Top = 161
  end
  object dtsFilho: TDataSource
    Left = 456
    Top = 232
  end
end
